export default {
  proteins: [
    "beans",
    "chicken",
    "codfish",
    "whitefish",
    "canned tuna",
    "tuna steak",
  ],
  carbs: [
    "boiled potatoes",
    "mashed potatoes",
    "roasted potatoes",
    "french fries",
    "pasta",
    "noisettes",
    "rice",
    "couscous",
  ],
  vegs: [
    "steemed broccoli",
    "lettuce",
    "tomatoes",
    "steemed carrots",
    "baked cauliflower",
    "roasted bell peppers",
    "baked aubergine",
  ],
  bigMeals: [
    {
      name: "spaghetti carbonara",
      ingredients: [
        "spaghetti",
        "bacon",
        "eggs",
        "parmesan cheese",
        "garlic",
        "olive oil",
      ],
    },
    {
      name: "lasagna",
      ingredients: [
        "lasagna pasta",
        "tomato sauce",
        "minced meat",
        "onions",
        "garlic",
        "milk",
        "flour",
      ],
    },
    {
      name: "fish pie",
      ingredients: [
        "white fish",
        "milk",
        "potatoes",
        "butter",
        "onions",
        "garlic",
      ],
    },
    {
      name: "peas and eggs",
      ingredients: [
        "peas",
        "tomatoes",
        "bacon",
        "carrots",
        "eggs",
        "onions",
        "garlic",
      ],
    },
    {
      name: "spaghetti bolognese",
      ingredients: [
        "spaghetti",
        "tomato sauce",
        "minced meat",
        "onions",
        "garlic",
      ],
    },
  ],
};
