export default {
  proteins: [
    "🌱 Beans",
    "🌱 Chickpeas",
    "🌱 Lentils",
    "🍗 Chicken",
    "🍖 Beef",
    "🐟 Codfish",
    "🐟 Whitefish",
    "🐟 Canned tuna",
    "🐟 Tuna steak",
    "🐟 Salmon",
  ],
  carbs: ["potatoes", "french fries", "pasta", "noisettes", "rice", "couscous"],
  vegs: [
    "broccoli",
    "lettuce",
    "tomatoes",
    "carrots",
    "cauliflower",
    "bell peppers",
    "aubergine",
    "beetroot",
    "peas",
  ],
  bigMeals: [
    {
      name: "🥓 Spaghetti carbonara",
      ingredients: [
        "spaghetti",
        "bacon",
        "eggs",
        "parmesan cheese",
        "garlic",
        "olive oil",
      ],
    },
    {
      name: "🍖 Lasagna",
      ingredients: [
        "lasagna pasta",
        "tomato sauce",
        "minced meat",
        "onions",
        "garlic",
        "milk",
        "flour",
      ],
    },
    {
      name: "🐟 Fish pie",
      ingredients: [
        "white fish",
        "milk",
        "potatoes",
        "butter",
        "onions",
        "garlic",
      ],
    },
    {
      name: "🥚 Peas and eggs",
      ingredients: [
        "peas",
        "tomatoes",
        "bacon",
        "carrots",
        "eggs",
        "onions",
        "garlic",
      ],
    },
    {
      name: "🍖 Spaghetti bolognese",
      ingredients: [
        "spaghetti",
        "tomato sauce",
        "minced meat",
        "onions",
        "garlic",
      ],
    },
  ],
};
